(function($){"use strict";$(document).ready(function(){function headerStyle(){if($('.main-header').length){var windowpos=$(window).scrollTop();var siteHeader=$('.main-header');var scrollLink=$('.scroll-top');if(windowpos>=250){siteHeader.addClass('fixed-header');scrollLink.fadeIn(300);}else{siteHeader.removeClass('fixed-header');scrollLink.fadeOut(300);}}}
headerStyle();var mobileWidth=992;var navcollapse=$('.navigation li.dropdown');navcollapse.hover(function(){if($(window).innerWidth()>=mobileWidth){$(this).children('ul').stop(true,false,true).slideToggle(300);$(this).children('.megamenu').stop(true,false,true).slideToggle(300);}});if($('.main-header .navigation li.dropdown ul').length){$('.main-header .navigation li.dropdown').append('<div class="dropdown-btn"><span class="fa fa-angle-down"></span></div>');$('.main-header .navigation li.dropdown .dropdown-btn').on('click',function(){$(this).prev('ul').slideToggle(500);$(this).prev('.megamenu').slideToggle(800);});$('.navigation li.dropdown > a').on('click',function(e){e.preventDefault();});}
if($('.main-header .main-menu').length){$('.main-header .main-menu .navbar-toggle').click(function(){$(this).prev().prev().next().next().children('li.dropdown').hide();});}
$('.nav-search > button').on('click',function(){$('.nav-search form').toggleClass('hide');});if($(window).width()>767){$('body').on('click',function(event){if($('.nav-search > button').has(event.target).length==0&&!$('.nav-search > button').is(event.target)&&$('.nav-search form').has(event.target).length==0&&!$('.nav-search form').is(event.target)){if($('.nav-search form').hasClass('hide')==false){$('.nav-search form').toggleClass('hide');};}});}
if($('.scroll-to-target').length){$(".scroll-to-target").on('click',function(){var target=$(this).attr('data-target');$('html, body').animate({scrollTop:$(target).offset().top},1000);});}
$('.team-member .image a').magnificPopup({type:'image',gallery:{enabled:true,navigateByImgClick:true,},});$(".project-filter li").on('click',function(){$(".project-filter li").removeClass("current");$(this).addClass("current");var selector=$(this).attr('data-filter');$('.project-active').imagesLoaded(function(){$(".project-active").isotope({itemSelector:'.item',filter:selector,});});});if($('.feedback-wrap').length){$('.feedback-wrap').slick({dots:true,infinite:false,autoplay:true,fade:true,autoplaySpeed:5000,arrows:false,centerMode:false,speed:1000,slidesToShow:1,slidesToScroll:1,});}
if($('.feedback-active').length){$('.feedback-active').slick({dots:true,infinite:true,autoplay:true,autoplaySpeed:5000,arrows:true,prevArrow:$('.feedback-prev'),nextArrow:$('.feedback-next'),centerMode:false,speed:1000,slidesToShow:3,slidesToScroll:2,responsive:[{breakpoint:1199,settings:{slidesToShow:2,}},{breakpoint:767,settings:{slidesToShow:1,slidesToScroll:1,}}]});}
if($('.feedback-three-wrap').length){$('.feedback-three-wrap').slick({dots:true,infinite:true,autoplay:true,autoplaySpeed:5000,arrows:false,appendDots:$('.slider-dots-area'),centerMode:false,speed:1000,slidesToShow:2,slidesToScroll:1,responsive:[{breakpoint:767,settings:{slidesToShow:1,}}]});}
if($('.dashboard-screenshot-wrap').length){$('.dashboard-screenshot-wrap').slick({dots:false,infinite:true,autoplay:true,autoplaySpeed:5000,arrows:true,prevArrow:'<button class="dashboard-prev"><i class="fas fa-arrow-left"></i></button>',nextArrow:'<button class="dashboard-next"><i class="fas fa-arrow-right"></i></button>',centerMode:true,centerPadding:'144px',slidesToShow:1,slidesToScroll:1,responsive:[{breakpoint:991,settings:{centerPadding:'50px',}},{breakpoint:575,settings:{centerPadding:'0',}}]});}
if($('.success-item').length){$('.success-item').appear(function(){var $t=$(this),n=$t.find(".count-text").attr("data-stop"),r=parseInt($t.find(".count-text").attr("data-speed"),10);if(!$t.hasClass("counted")){$t.addClass("counted");$({countNum:$t.find(".count-text").text()}).animate({countNum:n},{duration:r,easing:"linear",step:function(){$t.find(".count-text").text(Math.floor(this.countNum));},complete:function(){$t.find(".count-text").text(this.countNum);}});}},{accY:0});}
if($.fn.circleProgress){var progress1=$('.one.progress-content')
if($.fn.circleProgress){progress1.appear(function(){progress1.circleProgress({value:0.75,size:140,thickness:8,fill:"#5138ee",lineCap:'square',startAngle:-Math.PI/4*2,animation:{duration:2000},}).on('circle-animation-progress',function(event,progress){$(this).find('h2').html(Math.round(75*progress)+'<span>%</span>');});});};};if($.fn.circleProgress){var progress2=$('.two.progress-content')
if($.fn.circleProgress){progress2.appear(function(){progress2.circleProgress({value:0.89,size:140,thickness:8,fill:"#5138ee",lineCap:'square',startAngle:-Math.PI/4*2,animation:{duration:2000},}).on('circle-animation-progress',function(event,progress){$(this).find('h2').html(Math.round(89*progress)+'<span>%</span>');});});};};if($.fn.circleProgress){var progress3=$('.three.progress-content')
if($.fn.circleProgress){progress3.appear(function(){progress3.circleProgress({value:0.67,size:140,thickness:8,fill:"#5138ee",lineCap:'square',startAngle:-Math.PI/4*2,animation:{duration:2000},}).on('circle-animation-progress',function(event,progress){$(this).find('h2').html(Math.round(67*progress)+'<span>%</span>');});});};};$('select').niceSelect();if($('.wow').length){var wow=new WOW({boxClass:'wow',animateClass:'animated',offset:0,mobile:false,live:true});wow.init();}});$(window).on('resize',function(){var mobileWidth=992;var navcollapse=$('.navigation li.dropdown');navcollapse.children('ul').hide();navcollapse.children('.megamenu').hide();});$(window).on('scroll',function(){function headerStyle(){if($('.main-header').length){var windowpos=$(window).scrollTop();var siteHeader=$('.main-header');var scrollLink=$('.scroll-top');if(windowpos>=100){siteHeader.addClass('fixed-header');scrollLink.fadeIn(300);}else{siteHeader.removeClass('fixed-header');scrollLink.fadeOut(300);}}}
headerStyle();});$(window).on('load',function(){if($('.project-active').length){$(".project-active").isotope({itemSelector:'.item',});};function handlePreloader(){if($('.preloader').length){$('.preloader').delay(200).fadeOut(500);}}
handlePreloader();});$("a.page-scroll").on('click',function(event){if(this.hash!==""){event.preventDefault();var hash=this.hash;scrollToPosition(hash);}});function scrollToPosition(hash){$('body,html').animate({start:function(){},scrollTop:$(hash).offset().top,},1000,function(){window.location.hash=hash;});}})(window.jQuery);